# Generated by Django 5.2 on 2025-05-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EngTute', '0002_concept_subtitle_delete_concepts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='content',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='content',
        ),
    ]
