version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myapp_user -d myapp_db"]
      interval: 5s
      retries: 5

  web:
    build:
      context: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app    # bind-mount repo for live editing in dev
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
         # 👇 Add this line — this is what dj_database_url expects
      # - DATABASE_URL=postgres://myapp_user:mysecretpassword@db:5432/myapp_db
      
      - DB_NAME=myapp_db
      - DB_USER=myapp_user
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: