# Generated by Django 5.2.1 on 2025-06-02 14:47

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier; auto-generated', max_length=200, unique=True)),
                ('draft', models.BooleanField(default=False, help_text='Tick if this topic should remain in draft not show up in live site)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Controls display order')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier; auto-generated', max_length=200, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(default='')),
                ('draft', models.BooleanField(default=False, help_text='Tick if this topic should remain in draft not show up in live site)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Tutorial.concept')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Controls display order')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier; auto-generated', max_length=200, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(default='')),
                ('draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='Tutorial.topic')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('topic', 'slug')},
            },
        ),
    ]
